import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import esDict from '@/dictionaries/es.json';
import enDict from '@/dictionaries/en.json';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const dict = lang === 'en' ? enDict : esDict;

  return (
    <html>
      <body>
        <section>
          <Navbar lang={lang} dict={dict} />
          {children}
          <Footer />
          
        </section>
      </body>
    </html>

  );
}

